### ISSUE TITLE
apparently malb8dge doesnt like tab characters "	"

### ISSUE THREAD

**Issue by itsmebombie** [kr8gz/malb8dge.py#1]
it doesnt mind spaces but it doesnt like tabs
example:
```
print = (str): {
    ;str
}
print("abc") ### abc 
```
```
print = (str): {
	;str
}
print("abc") ### SyntaxError: expected a value, found '  '
```

**Comment by itsmebombie** [comment]
apparently github doesnt like them either and changed them to spaces in the title

**Comment by kr8gz** [comment]
i will add youre mom error

**Comment by itsmebombie** [comment]
pog

**Comment by itsmebombie** [comment]
btw your*

**Comment by kr8gz** [comment]
![image](https://user-images.githubusercontent.com/47776344/158835135-b5e715fa-af49-466e-9a29-45793d9f3cfc.png)

**Comment by itsmebombie** [comment]
true pog

**Comment by itsmebombie** [comment]
but like wouldnt it be better for it to convert tabs to spaces and rewrite the file
